# Generated by Django 5.2.11 on 2026-02-22 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='board/')),
                ('github_url', models.URLField(blank=True)),
                ('mastodon_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('is_current', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DjangoConEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('website_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('virtual', 'Virtual')], default='upcoming', max_length=20)),
                ('highlight', models.TextField(blank=True, help_text='One-line summary shown in the timeline.')),
            ],
            options={
                'verbose_name': 'DjangoCon Edition',
                'verbose_name_plural': 'DjangoCon Editions',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='GrantCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('application_url', models.URLField(blank=True)),
                ('max_amount', models.DecimalField(decimal_places=2, default=300, max_digits=8)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField(help_text='Guidance text shown on the grants page.')),
            ],
            options={
                'verbose_name': 'Grant Cycle',
            },
        ),
        migrations.CreateModel(
            name='SponsoredEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organizer', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('grant_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
