# Generated by Django 5.2.11 on 2026-03-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='bluesky_url',
            field=models.URLField(blank=True, verbose_name='Bluesky URL'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='X (Twitter) URL'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='mastodon_url',
            field=models.URLField(blank=True, verbose_name='Mastodon URL'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='Website URL'),
        ),
    ]
