# Generated by Django 5.2.11 on 2026-03-14 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_boardmember_bluesky_url_boardmember_linkedin_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown in the post listing.')),
                ('body', models.TextField()),
                ('author', models.CharField(blank=True, max_length=100)),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'ordering': ['-published_at'],
            },
        ),
    ]
