# Generated by Django 5.2.11 on 2026-03-14 17:17

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
