# Generated by Django 5.2.11 on 2026-03-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_blogpost_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='is_emeritus',
            field=models.BooleanField(default=False, help_text='Honour past members who went above and beyond.'),
        ),
    ]
